/* Generated By:JavaCC: Do not edit this line. DOTParserTreeConstants.java Version 4.2 */
package org.apache.pig.test.utils.dotGraph.parser;

public interface DOTParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTSTATEMENTLIST = 1;
  public int JJTSTATEMENT = 2;
  public int JJTSUBGRAPH = 3;
  public int JJTATTRIBUTESTATEMENT = 4;
  public int JJTNODESTATEMENT = 5;
  public int JJTEDGESTATEMENT = 6;
  public int JJTATTRIBUTELIST = 7;
  public int JJTATTRIBUTE = 8;
  public int JJTVALUE = 9;
  public int JJTNODENAME = 10;


  public String[] jjtNodeName = {
    "Parse",
    "StatementList",
    "Statement",
    "SubGraph",
    "AttributeStatement",
    "NodeStatement",
    "EdgeStatement",
    "AttributeList",
    "Attribute",
    "Value",
    "NodeName",
  };
}
/* JavaCC - OriginalChecksum=2f8afd3d281980d3c6a28434115c4e6f (do not edit this line) */
